// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Auction from "./islands/Auction.tsx";
import * as $Bidder from "./islands/Bidder.tsx";
import * as $Seller from "./islands/Seller.tsx";
import * as $bidd from "./islands/bidd.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Auction.tsx": $Auction,
    "./islands/Bidder.tsx": $Bidder,
    "./islands/Seller.tsx": $Seller,
    "./islands/bidd.tsx": $bidd,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
