name = "trwa/cardamove"
version = "0.0.0"
compiler = "v1.1.3"
plutus = "v3"
license = "AGPL-3.0"
description = "Aiken contracts for project 'trwa/cardamove'"

[repository]
user = "trwa"
project = "cardamove"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
