name:                cardamove
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/trwa/cardamove#readme
license:             MIT
author:              Lorenzo Fanton
maintainer:          887857@stud.unive.it
copyright:           2024 Lorenzo Fanton
category:            Blockchain
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - megaparsec == 9.5.0
  - text == 2.0.2
  - wide-word == 0.1.6.0

language: GHC2021

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs:        lib

executables:
  cardamove-cli:
    source-dirs:      src
    main:             Main.hs
    dependencies:
      - cardamove

tests:
  cardamove-test:
    source-dirs:      test
    main:             Spec.hs
    dependencies:
      - cardamove
      - hspec >= 2.11 && < 2.12
      - QuickCheck