name: aiken

on:
  push:
    branches: ["lore"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aiken-lang/setup-aiken@v0.1.0
        with:
          version: v1.0.26-alpha

      - run: cd examples && aiken fmt --check
      - run: cd examples && aiken check -D
      - run: cd examples && aiken build


